import type { Knex } from "knex";
import { db } from "../../../lib/knex/knex";
import { timestampCursorSelect } from "../../../lib/http/pagination/timestamp-cursor";
import { DoctorProfile } from "../../doctors/entity/doctor-profile.entity";
import type { DoctorProfileRow } from "../../doctors/types";
import { VerificationDocument } from "../entity/verification-document.entity";
import { IdentitySyncJobStatus } from "../enums";
import type { IdentitySyncJobRow, QueueQuery, UploadIntentRow, VerificationDocumentRow } from "../types";

export const DOCUMENT_COLUMNS = ["id", "doctor_profile_id", "type", "object_key", "file_type", "size_bytes", "status", "reviewed_by", "review_note", "created_at", "updated_at", "deleted_at"] as const;
export const INTENT_COLUMNS = ["id", "kind", "target_id", "owner_user_id", "document_type", "description", "quarantine_key", "max_bytes", "expires_at", "consumed_at", "result_id", "created_at"] as const;
export const JOB_COLUMNS = ["id", "doctor_profile_id", "doctor_user_id", "kind", "target_status", "reason", "actor_user_id", "request_id", "status", "attempts", "consecutive_failures", "last_error_code", "next_attempt_at", "succeeded_at", "created_at", "updated_at"] as const;
export const VERIFICATION_PROFILE_COLUMNS = ["id", "user_id", "headline", "bio", "years_experience", "consultation_fee", "currency", "default_slot_minutes", "timezone", "is_accepting_patients", "verification_status", "submitted_at", "reviewed_by", "review_note", "decided_at", "identity_sync_status", "suspended_at", "suspended_by", "suspension_reason", "created_at", "updated_at"] as const;

function toEntity(row: VerificationDocumentRow): VerificationDocument { return new VerificationDocument({ id: row.id, doctorProfileId: row.doctor_profile_id, type: row.type, objectKey: row.object_key, fileType: row.file_type, sizeBytes: row.size_bytes, status: row.status, reviewedBy: row.reviewed_by, reviewNote: row.review_note, createdAt: row.created_at, updatedAt: row.updated_at, deletedAt: row.deleted_at }); }
export async function findDocument(id: number, conn: Knex = db): Promise<VerificationDocument | undefined> { const row: VerificationDocumentRow | undefined = await conn<VerificationDocumentRow>("verification_documents").select(...DOCUMENT_COLUMNS).where({ id }).whereNull("deleted_at").first(); return row && toEntity(row); }
export async function findDocumentForUpdate(id: number, conn: Knex = db): Promise<VerificationDocument | undefined> { const row: VerificationDocumentRow | undefined = await conn<VerificationDocumentRow>("verification_documents").select(...DOCUMENT_COLUMNS).where({ id }).whereNull("deleted_at").forUpdate().first(); return row && toEntity(row); }
export async function listDocuments(profileId: number, conn: Knex = db): Promise<VerificationDocument[]> { const rows: VerificationDocumentRow[] = await conn<VerificationDocumentRow>("verification_documents").select(...DOCUMENT_COLUMNS).where("doctor_profile_id", profileId).whereNull("deleted_at").orderBy("id"); return rows.map(toEntity); }
export async function listDocumentsBatch(profileIds: number[], conn: Knex = db): Promise<Map<number, VerificationDocument[]>> { const result = new Map<number, VerificationDocument[]>(); if (!profileIds.length) return result; const rows: VerificationDocumentRow[] = await conn<VerificationDocumentRow>("verification_documents").select(...DOCUMENT_COLUMNS).whereRaw("doctor_profile_id = ANY(?::bigint[])", [profileIds]).whereNull("deleted_at").orderBy("id"); for (const row of rows) { const list = result.get(row.doctor_profile_id) ?? []; list.push(toEntity(row)); result.set(row.doctor_profile_id, list); } return result; }
export async function insertDocument(row: Pick<VerificationDocumentRow, "doctor_profile_id" | "type" | "object_key" | "file_type" | "size_bytes" | "status">, conn: Knex = db): Promise<VerificationDocument> { const rows: VerificationDocumentRow[] = await conn<VerificationDocumentRow>("verification_documents").insert(row).returning([...DOCUMENT_COLUMNS]); const inserted = rows[0]; if (!inserted) throw new Error("document_insert_empty"); return toEntity(inserted); }
export async function softDeleteDocument(id: number, conn: Knex = db): Promise<void> { await conn("verification_documents").where({ id }).whereNull("deleted_at").update({ deleted_at: conn.fn.now(), updated_at: conn.fn.now() }); }

export async function insertIntent(row: Pick<UploadIntentRow, "kind" | "target_id" | "owner_user_id" | "document_type" | "description" | "quarantine_key" | "max_bytes" | "expires_at">, conn: Knex = db): Promise<UploadIntentRow> { const rows: UploadIntentRow[] = await conn<UploadIntentRow>("upload_intents").insert(row).returning([...INTENT_COLUMNS]); const inserted = rows[0]; if (!inserted) throw new Error("intent_insert_empty"); return inserted; }
export async function findIntent(id: number, conn: Knex = db): Promise<UploadIntentRow | undefined> { return conn<UploadIntentRow>("upload_intents").select(...INTENT_COLUMNS).where({ id }).first(); }
export async function findIntentForUpdate(id: number, conn: Knex = db): Promise<UploadIntentRow | undefined> { return conn<UploadIntentRow>("upload_intents").select(...INTENT_COLUMNS).where({ id }).forUpdate().first(); }
export async function closeIntent(id: number, resultId: number | null = null, conn: Knex = db): Promise<void> { await conn("upload_intents").where({ id }).whereNull("consumed_at").update({ consumed_at: conn.fn.now(), result_id: resultId }); }
export async function listExpiredOpenIntents(limit = 500, conn: Knex = db): Promise<UploadIntentRow[]> { return conn<UploadIntentRow>("upload_intents").select(...INTENT_COLUMNS).where("kind", "verification_document").whereNull("consumed_at").where("expires_at", "<=", conn.fn.now()).orderBy("expires_at").limit(Math.min(500, Math.max(1, limit))); }
export async function deleteIntentsOlderThan(cutoff: Date, limit = 500, conn: Knex = db): Promise<number> { const ids: { id: number }[] = await conn<{ id: number }>("upload_intents").select("id").where("created_at", "<", cutoff).whereNotNull("consumed_at").orderBy("created_at").limit(Math.min(500, Math.max(1, limit))); if (!ids.length) return 0; return conn("upload_intents").whereIn("id", ids.map((row) => row.id)).delete(); }

export async function insertSyncJob(row: Pick<IdentitySyncJobRow, "doctor_profile_id" | "doctor_user_id" | "kind" | "target_status" | "reason" | "actor_user_id" | "request_id" | "status" | "next_attempt_at">, conn: Knex = db): Promise<IdentitySyncJobRow> { const rows: IdentitySyncJobRow[] = await conn<IdentitySyncJobRow>("identity_sync_jobs").insert(row).returning([...JOB_COLUMNS]); const inserted = rows[0]; if (!inserted) throw new Error("job_insert_empty"); return inserted; }
export async function findSyncJob(id: number, conn: Knex = db): Promise<IdentitySyncJobRow | undefined> { return conn<IdentitySyncJobRow>("identity_sync_jobs").select(...JOB_COLUMNS).where({ id }).first(); }
export async function findPendingSyncJob(profileId: number, conn: Knex = db): Promise<IdentitySyncJobRow | undefined> { return conn<IdentitySyncJobRow>("identity_sync_jobs").select(...JOB_COLUMNS).where({ doctor_profile_id: profileId, status: IdentitySyncJobStatus.Pending }).first(); }
export async function supersedePendingSyncJob(profileId: number, conn: Knex = db): Promise<void> { await conn("identity_sync_jobs").where({ doctor_profile_id: profileId, status: IdentitySyncJobStatus.Pending }).update({ status: IdentitySyncJobStatus.Superseded, updated_at: conn.fn.now() }); }
export async function updateSyncJob(id: number, changes: Partial<IdentitySyncJobRow>, conn: Knex = db): Promise<void> { await conn("identity_sync_jobs").where({ id }).update({ ...changes, updated_at: conn.fn.now() }); }
export async function claimDuePendingJobs(limit = 50, conn: Knex = db): Promise<IdentitySyncJobRow[]> { return conn.transaction(async (trx) => trx<IdentitySyncJobRow>("identity_sync_jobs").select(...JOB_COLUMNS).where("status", IdentitySyncJobStatus.Pending).where("kind", "verification").where("next_attempt_at", "<=", trx.fn.now()).orderBy("next_attempt_at").limit(Math.min(50, Math.max(1, limit))).forUpdate().skipLocked()); }

function toProfile(row: DoctorProfileRow): DoctorProfile { return new DoctorProfile({ id: row.id, userId: row.user_id, headline: row.headline, bio: row.bio, yearsExperience: row.years_experience, consultationFeeAmount: row.consultation_fee, currency: row.currency, defaultSlotMinutes: row.default_slot_minutes, timezone: row.timezone, isAcceptingPatients: row.is_accepting_patients, verificationStatus: row.verification_status, submittedAt: row.submitted_at, reviewedBy: row.reviewed_by, reviewNote: row.review_note, decidedAt: row.decided_at, identitySyncStatus: row.identity_sync_status, suspendedAt: row.suspended_at, suspendedBy: row.suspended_by, suspensionReason: row.suspension_reason, createdAt: row.created_at, updatedAt: row.updated_at }); }
export async function findProfileById(id: number, conn: Knex = db, lock = false): Promise<DoctorProfile | undefined> { let query = conn<DoctorProfileRow>("doctor_profiles").select(...VERIFICATION_PROFILE_COLUMNS).where({ id }).whereNull("deleted_at"); if (lock) query = query.forUpdate(); const row = await query.first(); return row ? toProfile(row) : undefined; }
export async function findProfileByUserId(userId: number, conn: Knex = db, lock = false): Promise<DoctorProfile | undefined> { let query = conn<DoctorProfileRow>("doctor_profiles").select(...VERIFICATION_PROFILE_COLUMNS).where({ user_id: userId }).whereNull("deleted_at"); if (lock) query = query.forUpdate(); const row = await query.first(); return row ? toProfile(row) : undefined; }
export async function touchProfile(id: number, conn: Knex = db): Promise<void> { await conn("doctor_profiles").where({ id }).whereNull("deleted_at").update({ updated_at: conn.fn.now() }); }
export async function isProfileLocallySuspended(userId: number, conn: Knex = db): Promise<boolean> { const row: { id: number } | undefined = await conn<{ id: number }>("doctor_profiles").select("id").where("user_id", userId).whereNull("deleted_at").whereNotNull("suspended_at").first(); return row !== undefined; }
export async function listQueue(query: QueueQuery, position: { timestamp: string; id: number } | undefined, conn: Knex = db): Promise<{ profile: DoctorProfile; cursorTimestamp: string }[]> { const sentinel = "9999-12-31T23:59:59.999999Z"; const timestamp = timestampCursorSelect(conn, "submitted_at", "cursor_timestamp"); let builder = conn<DoctorProfileRow & { cursor_timestamp: string | null }>("doctor_profiles").select(...VERIFICATION_PROFILE_COLUMNS, timestamp).whereNull("deleted_at").where("verification_status", query.status); if (position) builder = builder.whereRaw("(COALESCE(submitted_at, 'infinity'::timestamptz), id) > (?::timestamptz, ?)", [position.timestamp === sentinel ? "infinity" : position.timestamp, position.id]); const rows = await builder.orderByRaw("submitted_at ASC NULLS LAST, id ASC").limit(query.limit + 1) as unknown as Array<DoctorProfileRow & { cursor_timestamp: string | null }>; return rows.map((row) => ({ profile: toProfile(row), cursorTimestamp: row.cursor_timestamp ?? sentinel })); }


