import type { Socket } from "node:net";
import type { Express } from "express";
import type { InjectionToken } from "tsyringe";
import type { CryptoKey } from "jose";
import type { JwksCache } from "../../src/lib/auth/jwks-cache";
import type { UserTokenVerifier } from "../../src/lib/auth/user-token-verifier";
import type { MountedRouter } from "../../src/lib/http/types";
import type { Logger } from "../../src/lib/logger/logger";
import type { ObjectStorage } from "../../src/lib/storage/object-storage";

export interface BuildTestAppsOptions {
    publicRouters?: MountedRouter[];
    internalRouters?: MountedRouter[];
}

export interface TestApps {
    publicApp: Express;
    internalApp: Express;
}

export interface ContainerOverride {
    token: InjectionToken<unknown>;
    value: unknown;
}

export type FakeServerMode = "normal" | "slow" | "fail";

export interface FakeServerModeOptions {
    delayMs?: number;
    status?: number;
}

export interface FakeRoute {
    method: string;
    path: string;
    status: number;
    body?: unknown;
    /** Served verbatim instead of `JSON.stringify(body)` when set (malformed-response scenarios). */
    rawBody?: string;
    /** Default `application/json`. */
    contentType?: string;
}

export interface RecordedRequest {
    method: string;
    url: string;
    headers: Record<string, string | string[] | undefined>;
    body: string;
}

export interface FakeHttpServer {
    url: string;
    requests: RecordedRequest[];
    setMode(mode: FakeServerMode, options?: FakeServerModeOptions): void;
    close(): Promise<void>;
}

export interface LogCapture {
    lines(): Record<string, unknown>[];
    text(): string;
    restore(): void;
}

/** An operation that takes `Idempotency-Key`, and the component response it declares for 409. */
export interface IdempotentOperation {
    method: string;
    path: string;
    conflictResponse: string | undefined;
}

/** One proxied socket pair; `holed` pairs drop every byte in both directions (spec §9.4 round 2). */
export interface ProxiedConnection {
    client: Socket;
    upstream: Socket;
    holed: boolean;
}

export interface BlackHoleProxy {
    /** `postgres://…@127.0.0.1:<proxyPort>/…` — the target URL with host and port replaced. */
    url: string;
    /** Sockets accepted since the proxy started. */
    acceptedCount(): number;
    /** Every socket open NOW goes silent forever (no RST, no FIN); sockets accepted later are forwarded normally. */
    blackHoleEstablished(): void;
    close(): Promise<void>;
}

/** A fresh Ed25519 signing key for one test kid (spec §9.1: no key is ever committed to the repo). */
export interface SigningKey {
    kid: string;
    privateKey: CryptoKey;
    /** The public JWK as Identity publishes it (`kty, crv, x, kid, alg, use`). */
    publicJwk: Record<string, string>;
}

/** Overrides applied to the default user-token claims; `undefined` deletes the claim. */
export type ClaimOverrides = Record<string, unknown>;

export interface SignTokenOptions {
    /** Protected-header overrides (e.g. a different `kid` or `typ`); `undefined` deletes the member. */
    header?: Record<string, unknown>;
    /** Epoch seconds used for `iat` / `exp` defaults (default: now). */
    nowSeconds?: number;
}

/** A fake Identity JWKS endpoint (spec §9.1) built on `startFakeHttpServer`. */
export interface FakeJwks {
    /** `http://127.0.0.1:<port>/.well-known/jwks.json` */
    jwksUrl: string;
    /** Every key ever generated by this fake, by kid (also the removed ones, so tests can still sign with them). */
    keys: Map<string, SigningKey>;
    /** The key for `kid`; throws when the fake never generated it. */
    key(kid: string): SigningKey;
    /** Generates and publishes a new key. */
    addKey(kid: string): Promise<SigningKey>;
    /** Stops publishing `kid` (the key stays in `keys`). */
    removeKey(kid: string): void;
    /** Serves this raw body instead of the published set (`undefined` restores the set). */
    setBody(raw: string | undefined, contentType?: string): void;
    setMode(mode: FakeServerMode, options?: FakeServerModeOptions): void;
    requests: RecordedRequest[];
    close(): Promise<void>;
}

/** A controllable epoch-ms clock injected into a test `JwksCache`. */
export interface TestClock {
    now: () => number;
    advance: (ms: number) => void;
}

export interface FakeJwksCacheOptions {
    /** Injected clock (default: `Date.now`). */
    clock?: TestClock;
    /** Await one `refresh("boot")` before `fn` runs (default `true`). */
    prime?: boolean;
}

export interface FakeJwksWiring {
    cache: JwksCache;
    verifier: UserTokenVerifier;
}

/** `fakeLogger()`: jest mocks per level plus the `Logger`-typed view handed to the unit under test. */
export interface FakeLogger {
    debug: jest.Mock;
    info: jest.Mock;
    warn: jest.Mock;
    error: jest.Mock;
    metric: jest.Mock;
    logger: Logger;
    text(): string;
    messages(level: "debug" | "info" | "warn" | "error"): string[];
}

export interface StorageCall {
    operation: "createUploadPolicy" | "headObject" | "readHead" | "promote" | "delete" | "presignDownload";
    args: readonly (string | number)[];
}

export interface FakeStorage extends ObjectStorage {
    calls: StorageCall[];
    seed(key: string, bytes: Uint8Array): void;
    has(key: string): boolean;
    failNextCopy(): void;
    setHeadSize(key: string, sizeBytes: number): void;
    clear(): void;
}
